apiVersion: v1
kind: Service
metadata:
  name: gke-demo-service
  namespace: demo
spec:
  selector:
    app: gke-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
